# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "/tmp/log/gf-app/server"

# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true
#钉钉
[dingTalk]
    [dingTalk.default]
        sendUrl     = "https://oapi.dingtalk.com/robot/send"
        accessToken = "f06c463c2c4be4e2a3ce9bc7705cbcf3cabbf7a6e4b4587ccb4814fefd8c2f50"
        secret      = "SEC6b2e548aa7dcd97a115046926c5409f7bb8b6f0b35091c391cd692cc8de8c787"
    [dingTalk.wolf]
        sendUrl     = "https://oapi.dingtalk.com/robot/send"
        accessToken = "9bd6fd0671192e7544f05312fe0fd7ce3a723f3d5986a8dc33bbaab52a191ebf"
        secret      = "SEC4136f8310e4eae3645e384e3545a02fc0677cb8106cac3e79d5188727c6fba89"
#图灵
[tuLing]
    [tuLing.default]
        sendUrl = "http://openapi.tuling123.com/openapi/api/v2"
        apiKey  = "052ec04fa5984bdd931b5be0893bae91"
        userId  = "441453"